"""crear tabla usuarios

Revision ID: f88d4826b49a
Revises: b24c29a59fb8
Create Date: 2025-09-18 13:29:54.209591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88d4826b49a'
down_revision = 'b24c29a59fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
